// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsqGQVXDNDgTkyjEN3VGjgOwyq71lLC8g',
    appId: '1:769526432078:web:42b8833ecebf5f1575de1f',
    messagingSenderId: '769526432078',
    projectId: 'dues-26617',
    authDomain: 'dues-26617.firebaseapp.com',
    storageBucket: 'dues-26617.appspot.com',
    measurementId: 'G-NMJGDLQ14W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-qkF8XKqVs282bRVGGDXkaFNoqQsmo1s',
    appId: '1:769526432078:android:2681df916a4232eb75de1f',
    messagingSenderId: '769526432078',
    projectId: 'dues-26617',
    storageBucket: 'dues-26617.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJjnVwkgWba1L6ZZ1rw1KQ9jonoRLga10',
    appId: '1:769526432078:ios:69af2959800060fb75de1f',
    messagingSenderId: '769526432078',
    projectId: 'dues-26617',
    storageBucket: 'dues-26617.appspot.com',
    iosClientId: '769526432078-m9mn201ce3frfh6ffou30h4q6dim1pkn.apps.googleusercontent.com',
    iosBundleId: 'com.example.dues',
  );
}
